### ISSUE TITLE
Sidebar needs formatting

### ISSUE THREAD

**Issue by tbbooher** [tbbooher/cffc2#27]
- "latest news" isn't centered correctly
- also, the sidebar needs some separation (maybe something [like this](https://wordpress.org/support/topic/adding-dividing-line-to-separate-sidebar-from-main-content)) or maybe a darker gray background

**Comment by tbbooher** [comment]
i'm open for your ideas here, but the sidebar needs to look nice and separate -- while still preserving the simplicity of the page

**Comment by cbvasani** [comment]
Sidebar formatting updated. Please review it and let me know your feedback.

**Comment by tbbooher** [comment]
like it
