### ISSUE TITLE
logos are jumbled together when the page gets smaller

### ISSUE THREAD

**Issue by tbbooher** [tbbooher/cffc2#29]
![image](https://cloud.githubusercontent.com/assets/10830/15197393/38b210ca-179f-11e6-8488-cebba16b5a80.png)

**Comment by cbvasani** [comment]
Issue fixed, Please check.

**Comment by tbbooher** [comment]
ah, thanks

**Comment by tbbooher** [comment]
fixed, but waiting on #30 to make sure they remain centered as they are added or deleted.

**Comment by cbvasani** [comment]
Fixed, now logos will remain centered.

**Comment by tbbooher** [comment]
checking

**Comment by tbbooher** [comment]
works
