### ISSUE TITLE
front page update

### ISSUE THREAD

**Issue by tbbooher** [tbbooher/cffc2#30]
![front-page](https://cloud.githubusercontent.com/assets/10830/15214451/2699710e-181b-11e6-9bb2-11648beae54f.jpg)

Front page should match this -- the <pre>echo $image;</pre> would go into the wod image spot and you could you the $title and $content variables in the wod section.

You can use this:

should have code/content like this:

```
                <?php
                    $args = array( 'post_type' => 'wod', 'posts_per_page' => 1 );
                    $loop = new WP_Query( $args );
                    while ( $loop->have_posts() ) :
                      $loop->the_post();
                      $title = get_the_title();
                      $content = get_the_content();
                      $permalink = get_permalink( get_the_ID());
                      $num_comments =  get_comments_number();
                        if ( $num_comments == 0 ) {
                            $comments = __('No Comments');
                        } elseif ( $num_comments > 1 ) {
                            $comments = $num_comments . __(' Comments');
                        } else {
                            $comments = __('1 Comment');
                        }
                        $write_comments = '<a href="' . get_comments_link() .'">'. $comments.'</a>';
                      $image = get_the_post_thumbnail(get_the_ID(), 'medium', array( 'class' => 'img-thumbnail hidden-xs' ));
                    endwhile;
                    wp_reset_postdata();
                    if ($image == '') {
                        $image = '<img src="'.get_bloginfo('template_directory').'/img/Cookies.jpg">';
                    };
                ?>
                <?php echo $image; ?>
```

**Comment by tbbooher** [comment]
Front page should match this -- the <pre>echo $image;</pre> would go into the wod image spot and you could you the $title and $content variables in the wod section.

![front-page](https://cloud.githubusercontent.com/assets/10830/15214451/2699710e-181b-11e6-9bb2-11648beae54f.jpg)

**Comment by cbvasani** [comment]
Added new section as per mentioned above. Please check it and let me know if you have any query.

**Comment by tbbooher** [comment]
ok, to finish this out, I need to do some wordpress db editing to see if I can get this all to look right.

looks good so far.

**Comment by tbbooher** [comment]
[] I need to remove the extra content -- like testimonals

**Comment by tbbooher** [comment]
And get the daily wod to post

**Comment by tbbooher** [comment]
Can we get the sponsor images to center?

Also, what is that gray region underneath the sponsors? Could you please remove it? (I tried, but need a little help figuring it out.)

![2016-05-22 1](https://cloud.githubusercontent.com/assets/10830/15453643/30e694ec-1fec-11e6-867b-3d3e916e6eec.png)

**Comment by tbbooher** [comment]
Also, would like some space to be in the top. Please make it responsive, etc. 

![space](https://cloud.githubusercontent.com/assets/10830/15453671/dc722d8a-1fec-11e6-8b41-db390f7bc64d.png)

**Comment by tbbooher** [comment]
just need that space @cbvasani  and we can close this issue!

**Comment by cbvasani** [comment]
Done.

**Comment by tbbooher** [comment]
good.
