### ISSUE TITLE
footer

### ISSUE THREAD

**Issue by tbbooher** [tbbooher/cffc2#31]
Would like the footer to look roughly like this. It is to roughly match: www.crossfitadaptation.com

Feel free to take liberties and get the colors right, but this is the layout and sections.

![footer](https://cloud.githubusercontent.com/assets/10830/15214677/68ec0200-181c-11e6-87b7-af28ecb473a7.jpg)

**Comment by cbvasani** [comment]
Footer added. Please review it and let me know your feedback.

**Comment by cbvasani** [comment]
I have created footer elements on left if you want to centralize all element, it will look like this.
![image](https://cloud.githubusercontent.com/assets/10550428/15345384/092884ba-1ccc-11e6-851a-b8a5bd737e7e.png)

**Comment by cbvasani** [comment]
Please let me know your thoughts.

**Comment by tbbooher** [comment]
checking to see if it is responsive.

**Comment by tbbooher** [comment]
wow -- great work
