### ISSUE TITLE
need to change the Login button to Get Started

### ISSUE THREAD

**Issue by tbbooher** [tbbooher/cffc2#32]
And it should link to the Get Started Page
![2016-05-22 4](https://cloud.githubusercontent.com/assets/10830/15453701/806cbcde-1fed-11e6-866a-3f7926830bc6.jpg)

**Comment by cbvasani** [comment]
Done. Please check it.

**Comment by tbbooher** [comment]
looking now

**Comment by tbbooher** [comment]
works -- closing -- good work @cbvasani
