### ISSUE TITLE
I moved the site. The slider is out of control

### ISSUE THREAD

**Issue by tbbooher** [tbbooher/cffc2#34]
look at: http://new.crossfitfallschurch.com/

the database and files are the same. any idea what is going wrong?

**Comment by cbvasani** [comment]
There is jQuery missing for slider. I have checked in console, slider jQuery file getting wrong path.

![untitled-1](https://cloud.githubusercontent.com/assets/10550428/15459648/f9d3e5b6-20c4-11e6-8224-e5101e427d32.jpg)

**Comment by tbbooher** [comment]
good catch --

**Comment by tbbooher** [comment]
can you fix this -- or tell me how to fix it?

**Comment by tbbooher** [comment]
plugin?

**Comment by tbbooher** [comment]
the databases are the same -- and the back-ends should be the same as well. hmm . . .

**Comment by tbbooher** [comment]
anyway -- please let me know how to move this forward? do you need more hours?

**Comment by cbvasani** [comment]
I am not getting why is this happen, to fix it I need ftp and admin details.

**Comment by tbbooher** [comment]
ok, i got this. i'll transfer it to me.

**Comment by tbbooher** [comment]
fixed
